kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven
  commands:
  - java -version
  - mvn -version -B

- name: frontend
  image: maven:3-jdk-10
  commands:
  - mvn -version
  settings:
    user: fabman
    tags:
      - 1
      - 1.0
    yo: 234
