kind: pipeline
type: docker
name: default

steps:
- name: build
  image: maven
  commands:
  - ls -l
  - touch EINS.txt

- name: frontend
  image: maven:3-jdk-10
  commands:
  - ls -l
  settings:
    user: fabman
    tags:
      - 1
      - 1.0
    yo: 234
